# Generated by Django 3.1.1 on 2020-10-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdif_app', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.FileField(blank=True, upload_to='plantuml', verbose_name='plantuml'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='クラス図'),
        ),
    ]
